// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAq3fC-5OGFP8Ap2hjXvsnOlXZi1FAPQ',
    appId: '1:512341840743:web:7f83dc6721952c698d95c2',
    messagingSenderId: '512341840743',
    projectId: 'mungnyan-1961c',
    authDomain: 'mungnyan-1961c.firebaseapp.com',
    storageBucket: 'mungnyan-1961c.appspot.com',
    measurementId: 'G-1YD5TY0Q2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUo906mUZk4oWPcSjgdWQP2h-nQKMWvA',
    appId: '1:512341840743:android:5e4fd1658a3c53128d95c2',
    messagingSenderId: '512341840743',
    projectId: 'mungnyan-1961c',
    storageBucket: 'mungnyan-1961c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-KHsOoEltMjPIOHxRgHo-MM0B0iLf-U',
    appId: '1:512341840743:ios:4d96d06f0ae150458d95c2',
    messagingSenderId: '512341840743',
    projectId: 'mungnyan-1961c',
    storageBucket: 'mungnyan-1961c.appspot.com',
    iosBundleId: 'com.vranchat.vranchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpAq3fC-5OGFP8Ap2hjXvsnOlXZi1FAPQ',
    appId: '1:512341840743:web:da436cbc57b452088d95c2',
    messagingSenderId: '512341840743',
    projectId: 'mungnyan-1961c',
    authDomain: 'mungnyan-1961c.firebaseapp.com',
    storageBucket: 'mungnyan-1961c.appspot.com',
    measurementId: 'G-CZ6VEKL3QF',
  );
}
